### ISSUE TITLE
Oprava domácího úkolu: Životopis

### ISSUE THREAD

**Issue by LenkaVer** [SlavkaVavrinova/zivotopis#1]
Ahoj Slávko,

super práce, vidím, že s flexem jste už velcí kámoši a chválím použití BEMu a media queries.
Doporučila bych se zaměřit na přehlednost kódu a obrázky bych pro přehlednost v repozitáři uložila do složky (to jen taková drobnost).
Ve footeru zarovnáváš na střed pomocí text-align a flexu align-items a justify content, ten text-align se mi tam zdá už zbytečný.

**Comment by SlavkaVavrinova** [comment]
Leni děkuji, máš pravdu, složku jsem přidala. Já na začátku neměla v plánu tam dát tolik obrázků a trochu se to zvrhlo :-)

Opravu jsem uložila a jdu na další úkol :)
